# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np 


#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'1.24.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
arr.itemsize*arr.size

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
arr[4]=1 
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
a=np.arange(10,50) 
a 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [24]:
a = np.arange(0,9).reshape(3,3)
a 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [26]:

np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [29]:
np.random.random((3,3))

array([[0.69000727, 0.76874551, 0.58249071],
       [0.05421354, 0.51949623, 0.9985683 ],
       [0.09984849, 0.63668252, 0.5229883 ]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [31]:
a=np.random.rand(10,10)
np.min(a), np.max(a)

(0.011655973250215945, 0.9789850717452034)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [35]:
a=np.random.rand(30)
a
np.mean(a)


0.5294042014850305

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [65]:
a= np.ones((10,10))
a
a[1:-1,1:-1]=0 
a


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [75]:
arr=np.random.random((3,3)) 
arr
np.pad(arr,pad_width=1) 


array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.6384663 , 0.96653432, 0.71536204, 0.        ],
       [0.        , 0.40838717, 0.65040488, 0.00753076, 0.        ],
       [0.        , 0.67816276, 0.48148777, 0.06933534, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [127]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [79]:
np.diag(np.arange(1,5),k=-1) 

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [96]:
a=np.zeros((8,8)) 
a
a[1::2 ,::2]=1 
a[::2  ,1::2]=1
a 

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [97]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [103]:
a= np.zeros((8,8))
np.tile([[0,1],[1,0]],(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [135]:
a =np.random.random((5,5))
a
arr=(a- np.mean (a)) / (np.std (a))
arr 

array([[-1.67971897,  1.85823524, -1.24936715,  0.02446945, -1.19090426],
       [ 0.03226407, -0.28967228,  0.34909145, -0.33176333,  0.96982175],
       [-0.09925239,  1.54949163, -1.01594635,  0.11516068,  0.27367991],
       [ 0.42422921,  0.25187345, -0.79100534,  0.39078558, -1.96489146],
       [-0.22914906,  1.70799433, -0.06868656, -0.66645409,  1.62971449]])

23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [110]:
arr=([("r",np.ubyte),("g",np.ubyte),("b",np.ubyte),("a",np.ubyte)])  
arr

[('r', numpy.uint8),
 ('g', numpy.uint8),
 ('b', numpy.uint8),
 ('a', numpy.uint8)]

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [117]:
a = np.dot(np.random.random((5,3)), np.random.random((3,2))) 
a

array([[0.82943134, 0.43366194],
       [1.22092254, 0.55768045],
       [0.89329228, 0.90305911],
       [0.8752719 , 0.54874606],
       [0.99231311, 0.49340841]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [124]:
a =np.arange(0,10) 
a[(3<a)&(a<8)]*=-1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [126]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [134]:
 all


C:\Users\Compu City\AppData\Local\Temp\ipykernel_6856\1120146665.py:1: RuntimeWarning: invalid value encountered in power
  z**z


array([[0.69220259,        nan, 0.94125636, 1.15642434, 0.7974604 ],
       [0.9332507 , 1.50082062,        nan,        nan, 1.85293395],
       [       nan, 1.22928493,        nan, 1.1328963 ,        nan],
       [1.25317685,        nan,        nan,        nan,        nan],
       [0.70530746,        nan, 1.17549081, 0.7013239 ,        nan]])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [136]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Compu City\AppData\Local\Temp\ipykernel_6856\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\Compu City\AppData\Local\Temp\ipykernel_6856\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\Compu City\AppData\Local\Temp\ipykernel_6856\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [137]:
a = np.random.uniform(-10,+10,10) 
np.where(a>0,np. ceil(a), np.floor(a))

array([-10.,  -4.,  -8.,  -1.,   6.,  -2.,  -4.,  -4.,   2.,  -6.])

#### 30. How to find common values between two arrays? (★☆☆)

In [140]:
a = np.random.randint(0,9,10) 
b = np.random.randint(0,9,10)
np.intersect1d(a,b) 

array([0, 3, 4, 6])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [148]:
np.seterr(all=None, divide=None, over=None, under=None, invalid=None)



{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [149]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [158]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1) 
yesterday ,today , tomorrow
 

(numpy.datetime64('2024-02-25'),
 numpy.datetime64('2024-02-26'),
 numpy.datetime64('2024-02-27'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [161]:
a = np.arange('2016-07','2016-08', dtype='datetime64[D]') 
a

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [172]:
A = np.random.random(3)*1
B = np.random.random(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-0.65490707, -0.94260321, -0.16367045])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [170]:
a = np.random.uniform(0,5,5)
a - a%1 # 1st
a // 1  #2nd
np.floor(a) #3rd
a.astype(int) #4th
np.trunc(a) #5th

array([2., 4., 2., 1., 2.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [164]:
a =np.zeros((5,5)) 
a+= np.arange(0,5) 
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [177]:
def generate():
    for x in range(10):
        yield x
y = np.fromiter(generate(),dtype=float,count=-1)
y

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [179]:
a=np.linspace(0,1,11,endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [180]:
a=np.sort(np.random.random(10)) 
a

array([0.00936337, 0.12757963, 0.20987657, 0.27554405, 0.30861934,
       0.33402358, 0.56381356, 0.70892541, 0.96130231, 0.96499192])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [184]:
x = np.arange(5)
np.add.reduce(x)

10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [189]:
a = np.random.randint(0,9,10) 
b = np.random.randint(0,9,10)
eq = np.allclose(A,B)
print(eq)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [194]:
arr = np.arange(0,10) 
arr 
arr.flags.writeable = False
arr[2]=3

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [207]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
R
T

array([1.54357995, 1.08911478, 1.21310514, 0.98319219, 0.97056734,
       1.52263937, 1.03236932, 0.1091954 , 0.64469348, 0.95810328])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [205]:
x =np.random.random(10) 
x[x.argmax()]=0 
x

array([0.49844323, 0.        , 0.73153255, 0.80544941, 0.13197535,
       0.79218378, 0.51410893, 0.59556129, 0.89125991, 0.3624047 ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [208]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [209]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [210]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [221]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((50,50))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [222]:
x = np.arange(100)
y = np.random.uniform(0,100)
index = (np.abs(x-y)).argmin()
print(x[index])

99


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [224]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
a

C:\Users\Compu City\AppData\Local\Temp\ipykernel_6856\3611676502.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [ ('position', [ ('x', float, 1),


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [227]:
import scipy.spatial
Z = np.random.random((100,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.73997475 0.39265096 0.81279497 0.9473333  0.86311148
  1.09937814 0.57934583 0.91321919 0.98098214]
 [0.73997475 0.         0.44237728 0.67817427 0.21205574 0.1840913
  0.39544887 0.40255409 0.27995325 0.40776716]
 [0.39265096 0.44237728 0.         0.8454118  0.65120058 0.61187243
  0.83716858 0.18870339 0.54084342 0.79943201]
 [0.81279497 0.67817427 0.8454118  0.         0.73318568 0.59847877
  0.72202089 0.94993158 0.9551589  0.48159844]
 [0.9473333  0.21205574 0.65120058 0.73318568 0.         0.13618811
  0.20180762 0.58532374 0.29954757 0.3236444 ]
 [0.86311148 0.1840913  0.61187243 0.59847877 0.13618811 0.
  0.23654114 0.58656832 0.39051696 0.23157436]
 [1.09937814 0.39544887 0.83716858 0.72202089 0.20180762 0.23654114
  0.         0.7850192  0.48562091 0.24359646]
 [0.57934583 0.40255409 0.18870339 0.94993158 0.58532374 0.58656832
  0.7850192  0.         0.39966312 0.8037835 ]
 [0.91321919 0.27995325 0.54084342 0.9551589  0.29954757 0.39051696
  0.48562091 0.399663

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [232]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[69  8 56 92 97 63 83 46 40 80]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [247]:
s=string(1, 2, 3, 4, 5,
6,  ,  , 7, 8
 ,  , 9,10,11) 
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z) 

SyntaxError: invalid syntax (3405396295.py, line 2)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [248]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [249]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [250]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [252]:
X = np.random.rand(3, 3)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[ 0.22394925, -0.15148082, -0.07246843],
       [ 0.23904111, -0.17422535, -0.06481576],
       [-0.1476681 ,  0.43437131, -0.28670321]])

#### 59. How to sort an array by the nth column? (★★☆)

In [260]:
Z = np.random.randint(0,10,(3,3))
print(Z) 
Z[Z[:,1].argsort()]

[[4 5 2]
 [4 4 7]
 [5 7 3]]


array([[4, 4, 7],
       [4, 5, 2],
       [5, 7, 3]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [265]:
Z = np.random.randint(0,3,(3,10))
(~Z.any(axis=0)).any()

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [269]:
x = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(x - z).argmin()]
print(m)

1


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [270]:
x =np.arange(0,3).reshape(1,3)
y =np.arange(0,3).reshape(3,1)
iterator = np.nditer([x,y,None])
for x,y,z in iterator: z[...] = x + y
print(iterator.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [3]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)  

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [272]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[5. 1. 3. 1. 4. 1. 4. 3. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [274]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [5]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3), dtype=np.uint8)

I24 = np.dot(I.astype(np.uint32), [1, 256, 65536])

n = len(np.unique(I24))
n 

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [276]:
x = np.random.randint(0,10,(3,4,3,4))
sum = x.sum(axis=(-2,-1))
(sum)

array([[70, 57, 51, 59],
       [50, 47, 67, 43],
       [61, 55, 69, 51]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [277]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.55152329 0.4007685  0.48673028 0.68096919 0.53784882 0.61228775
 0.51458371 0.34825486 0.44833933 0.55638206]


#### 69. How to get the diagonal of a dot product? (★★★)

In [285]:
x = np.random.uniform(0,1,(3,3))
y = np.random.randint(0,1,(3,3))
np.diag(np.dot(x, y))



array([0., 0., 0.])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [6]:

x = np.array([1, 2, 3, 4, 5])
y = 3
z = np.zeros(len(x) + (len(x)-1)*(y))
z[::y+1] = x
print(z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [289]:
A = np.ones((5,5,3))
B = 3*np.ones((5,5))
A * B[:,:,None]

array([[[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]])

#### 72. How to swap two rows of an array? (★★★)

In [291]:
A = np.arange(9).reshape(3,3)
A
A[[0,1]] = A[[1,0]]
A

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [7]:

faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F)*3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
print(G) 

[(10, 23) (10, 29) (10, 56) (10, 67) (14, 45) (14, 52) (23, 67) (25, 51)
 (25, 61) (27, 31) (27, 83) (29, 56) (31, 83) (35, 65) (35, 85) (45, 52)
 (48, 51) (48, 95) (51, 61) (51, 69) (51, 76) (51, 95) (59, 69) (59, 78)
 (65, 85) (69, 76) (69, 78) (82, 92) (82, 96) (92, 96)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [9]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
A 

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [10]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1)) 

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [12]:
from numpy.lib import stride_tricks


def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)


Z = rolling(np.arange(10), 3)
print(Z) 

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [294]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.50886575, -0.06431802,  0.41503531,  0.06226036, -0.35712884,
        0.1981001 ,  0.15116018,  0.91289225,  0.42155859, -0.73593651,
       -0.57169034,  0.45739243,  0.22368604,  0.97058247,  0.17080215,
        0.03046054,  0.05172694,  0.63515728,  0.72962438,  0.40576957,
        0.97859697,  0.7495268 , -0.94818957,  0.01224511,  0.22846102,
       -0.47976824, -0.64084966, -0.91048569,  0.09156676, -0.68735664,
       -0.81406367, -0.60740128, -0.71446089, -0.32876175, -0.76502618,
        0.01612264, -0.37445317, -0.63359749, -0.74773578,  0.72410061,
       -0.07927046, -0.58816684, -0.22758256, -0.15193723, -0.24645673,
        0.66554687,  0.50382704, -0.81581553,  0.16717255,  0.24621045,
        0.82261366,  0.05430958,  0.49683742,  0.55217921,  0.70283319,
        0.35648166,  0.40500851,  0.87188395, -0.69034455, -0.71142651,
        0.8785141 ,  0.5633667 ,  0.99907107,  0.79642403, -0.59880145,
        0.32427515, -0.64831697, -0.32170201,  0.67675239, -0.46

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [13]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:, 0]-p[..., 0])*T[:, 0] + (P0[:, 1]-p[..., 1])*T[:, 1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))


P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))
print(distance(P0, P1, p)) 

[ 2.61476851  4.45706209 10.33514831  8.14554139  1.44888474  5.06050447
  3.12840706  8.12977856  7.99738617  0.74085045]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [15]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:, 0]-p[..., 0])*T[:, 0] + (P0[:, 1]-p[..., 1])*T[:, 1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2)) 
print(np.array([distance(P0, P1,p_i) for p_i in p])) 

[[9.81841597e+00 9.48272100e+00 3.65918100e+00 7.64823102e+00
  2.58057415e+00 8.02853746e+00 4.81235827e+00 8.42868379e-01
  9.89655814e+00 7.15081454e+00]
 [2.46258357e+00 1.16620745e+01 8.54152964e+00 2.47859275e-01
  7.34764229e+00 1.07485243e+01 1.20421298e+00 3.79435256e+00
  1.45338783e+01 6.30525542e+00]
 [6.20639851e+00 8.96639982e+00 5.39320435e-02 4.83307436e+00
  2.78535776e+00 7.65924866e+00 2.28889427e+00 6.75356910e-01
  1.00640980e+01 3.59270798e+00]
 [3.99296062e+00 3.16329812e+00 2.23522232e+00 8.03739530e-02
  2.76539086e+00 1.88947251e+00 2.83170231e+00 6.24459469e+00
  4.49487412e+00 3.30639101e+00]
 [8.01184160e+00 1.30407668e+01 1.91154166e+00 8.34605013e+00
  6.63111933e+00 1.16996129e+01 6.03628949e+00 3.18600844e+00
  1.39254516e+01 4.05376936e+00]
 [6.81482427e+00 1.40579697e+00 5.49899910e-01 1.08731940e+00
  5.16089775e+00 5.25711191e-03 2.26792948e+00 8.60926933e+00
  2.13017588e+00 6.83210033e+00]
 [1.68439204e+00 4.93061481e+00 7.86439839e+00 2.92144974e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [22]:
import numpy as np

Z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
fill = 0
position = (1, 1)

R = np.ones(shape, dtype=Z.dtype) * fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P - Rs // 2)
Z_stop = (P + Rs // 2) + Rs % 2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.minimum(R_stop, (R_stop - np.maximum(Z_stop - Zs, 0))).tolist()
Z_stop = (np.minimum(Z_stop, Zs)).tolist()

# Convert the indices to integers
r = [slice(int(start), int(stop)) for start, stop in zip(R_start, R_stop)]
z = [slice(int(start), int(stop)) for start, stop in zip(Z_start, Z_stop)]

# Assign values from Z to R using slices
R[r[0], r[1]] = Z[z[0], z[1]]

print(Z) 
print(R)  

[[9 8 1 1 8 0 7 9 3 2]
 [5 9 6 1 0 2 7 5 4 5]
 [7 6 8 8 7 3 7 5 0 5]
 [2 2 0 4 2 7 5 7 5 9]
 [5 1 6 9 8 3 1 1 5 5]
 [5 2 9 2 5 1 5 2 0 7]
 [2 4 6 3 5 6 9 8 5 1]
 [9 9 5 9 6 7 9 9 4 9]
 [3 2 1 5 2 5 0 6 7 3]
 [6 7 6 7 3 3 6 5 0 1]]
[[0 0 0 0 0]
 [0 9 8 1 1]
 [0 5 9 6 1]
 [0 7 6 8 8]
 [0 2 2 0 4]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [23]:
Z = np.arange(1, 15, dtype=np.uint32)
R = stride_tricks.as_strided(Z, (11, 4), (4, 4))
print(R) 

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [34]:
Z = np.random.uniform(0, 1,(10,10)) 
rank = np.linalg.matrix_rank(Z)
print(rank)  

10


#### 83. How to find the most frequent value in an array?

In [33]:
Z = np.random.randint(0, 10, 50) 
x =np.bincount(Z).argmax()
x  

2

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [35]:
Z = np.random.randint(0, 5, (10, 10))
print(sliding_window_view(Z, window_shape=(3, 3))) 

[[[[2 3 4]
   [1 4 3]
   [2 1 0]]

  [[3 4 3]
   [4 3 4]
   [1 0 3]]

  [[4 3 4]
   [3 4 3]
   [0 3 0]]

  [[3 4 1]
   [4 3 4]
   [3 0 0]]

  [[4 1 3]
   [3 4 4]
   [0 0 3]]

  [[1 3 1]
   [4 4 3]
   [0 3 0]]

  [[3 1 3]
   [4 3 1]
   [3 0 2]]

  [[1 3 4]
   [3 1 0]
   [0 2 0]]]


 [[[1 4 3]
   [2 1 0]
   [1 1 0]]

  [[4 3 4]
   [1 0 3]
   [1 0 4]]

  [[3 4 3]
   [0 3 0]
   [0 4 4]]

  [[4 3 4]
   [3 0 0]
   [4 4 1]]

  [[3 4 4]
   [0 0 3]
   [4 1 3]]

  [[4 4 3]
   [0 3 0]
   [1 3 2]]

  [[4 3 1]
   [3 0 2]
   [3 2 2]]

  [[3 1 0]
   [0 2 0]
   [2 2 1]]]


 [[[2 1 0]
   [1 1 0]
   [0 4 2]]

  [[1 0 3]
   [1 0 4]
   [4 2 3]]

  [[0 3 0]
   [0 4 4]
   [2 3 1]]

  [[3 0 0]
   [4 4 1]
   [3 1 1]]

  [[0 0 3]
   [4 1 3]
   [1 1 2]]

  [[0 3 0]
   [1 3 2]
   [1 2 0]]

  [[3 0 2]
   [3 2 2]
   [2 0 4]]

  [[0 2 0]
   [2 2 1]
   [0 4 1]]]


 [[[1 1 0]
   [0 4 2]
   [0 2 3]]

  [[1 0 4]
   [4 2 3]
   [2 3 4]]

  [[0 4 4]
   [2 3 1]
   [3 4 0]]

  [[4 4 1]
   [3 1 1]
   [4 0 0]]

  [[4 1 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [36]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)


def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)


S = symetric(np.random.randint(0, 10, (5, 5)))
S[2, 3] = 42
print(S) 

[[ 1  9  5  9  4]
 [ 9  7  6  5 15]
 [ 5  6  0 42  3]
 [ 9  5 42  1  9]
 [ 4 15  3  9  4]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [37]:
p, n = 10, 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)  

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [38]:
Z = np.ones((16, 16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                    np.arange(0, Z.shape[1], k), axis=1)
print(S)  

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [59]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
         Z[1:-1, 0:-2] + Z[1:-1, 2:] +
         Z[2:, 0:-2] + Z[2:, 1:-1] + Z[2:, 2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1, 1:-1] == 1)
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z


Z = np.random.randint(0, 2, (50, 50))
for i in range(100):
    Z = iterate(Z)
print(Z) 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [40]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 3 

# Slow
print(Z[np.argsort(Z)[-n:]]) 

[9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [41]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix


print(cartesian(([1, 2, 3], [4, 5], [6, 7]))) 

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [45]:
a = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
res = np.core.records.fromarrays(a.T,
                                 names='a, b, c') 
print(res) 

[('Hello', '2.5', '3') ('World', '3.6', '2')]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [46]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x) 

2.96 s ± 250 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
494 ms ± 34.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
270 ms ± 24.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [48]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3, 1)).all(1))[0]
print(rows) 

[0 4 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [49]:
Z = np.random.randint(0, 5, (10, 3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:, 1:] == Z[:, :-1], axis=1)
U = Z[~E]
print(U) 

[[1 3 4]
 [4 2 1]
 [3 1 2]
 [0 2 1]
 [1 4 3]
 [2 0 4]
 [3 0 4]
 [2 2 0]
 [0 2 4]
 [3 2 0]]
[[1 3 4]
 [4 2 1]
 [3 1 2]
 [0 2 1]
 [1 4 3]
 [2 0 4]
 [3 0 4]
 [2 2 0]
 [0 2 4]
 [3 2 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [50]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1, 1) & (2**np.arange(8))) != 0).astype(int)
print(B[:, ::-1]) 

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [51]:
Z = np.random.randint(0, 2,(6,3)) 
uZ = np.unique(Z, axis=0)
print(uZ) 

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [52]:
A = np.random.uniform(0, 1, 10)
B = np.random.uniform(0, 1, 10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B)  # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B 

array([[2.08671656e-02, 1.14935656e-02, 3.09715551e-03, 1.78922230e-02,
        1.03114228e-02, 8.57613568e-03, 1.56759326e-02, 2.34117330e-02,
        5.21586912e-04, 1.34180910e-02],
       [1.56581601e-01, 8.62446264e-02, 2.32402222e-02, 1.34258430e-01,
        7.73741440e-02, 6.43530163e-02, 1.17627983e-01, 1.75675350e-01,
        3.91384795e-03, 1.00685747e-01],
       [7.66434761e-01, 4.22149725e-01, 1.13756113e-01, 6.57167430e-01,
        3.78730536e-01, 3.14994792e-01, 5.75764809e-01, 8.59894742e-01,
        1.91574815e-02, 4.92836043e-01],
       [7.38540637e-01, 4.06785734e-01, 1.09615999e-01, 6.33250052e-01,
        3.64946771e-01, 3.03530667e-01, 5.54810051e-01, 8.28599175e-01,
        1.84602517e-02, 4.74899449e-01],
       [5.21711126e-01, 2.87356759e-01, 7.74336351e-02, 4.47332999e-01,
        2.57801374e-01, 2.14416538e-01, 3.91922343e-01, 5.85329212e-01,
        1.30404723e-02, 3.35472842e-01],
       [1.40323403e-03, 7.72896654e-04, 2.08271411e-04, 1.20318095e-03,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [54]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5  # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200)  # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y) 

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [55]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M]) 

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [56]:
X = np.random.randn(100)  # random 1D array
N = 1000  # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint) 

[-0.18908846  0.18945059]
